/* eslint-disable no-unused-vars */
import React from "react";
import { Table } from "antd";

const columns = [
  {
    title: "Lubricant Name",
    dataIndex: "name",
    filters: [
      {
        text: "Eni Blasia S 320",
        value: "Eni Blasia S 320",
      },
      {
        text: "Shell Omala S2 G220",
        value: "Shell Omala S2 G220",
      },
      {
        text: "Enerpac",
        value: "Enerpac",
      },
      {
        text: "Shell Omala S4 WE 320",
        value: "Shell Omala S4 WE 320",
      },
      {
        text: "Mobilgear 600 XP 220",
        value: "Mobilgear 600 XP 220",
      },
      {
        text: "LUBCON Turmowood Oil 1",
        value: "LUBCON Turmowood Oil 1",
      },
      {
        text: "Shell Omala S2 GX 220",
        value: "Shell Omala S2 GX 220",
      },
      {
        text: "CLP PG 220",
        value: "CLP PG 220",
      },
      {
        text: "Gear Oil Base 220 E1",
        value: "Gear Oil Base 220 E1",
      },
      {
        text: "CLP 680 Oil",
        value: "CLP 680 Oil",
      },
      {
        text: "CLP PG 460",
        value: "CLP PG 460",
      },
      {
        text: "Shell Tellus S2 M 32",
        value: "Shell Tellus S2 M 32",
      },
      {
        text: "بهران بردبار 220",
        value: "بهران بردبار 220",
      },
      {
        text: "بهران بردبار PS 220",
        value: "بهران بردبار PS 220",
      },
      {
        text: "بهران بردبار PG 220",
        value: "بهران بردبار PG 220",
      },
      {
        text: "بهران بردبار PG 460",
        value: "بهران بردبار PG 460",
      },
      {
        text: "بهران بردبار PG 320",
        value: "بهران بردبار PG 320",
      },
      {
        text: "بهران بردبار 680",
        value: "بهران بردبار 680",
      },
      {
        text: "بهران هیدرولیک H46",
        value: "بهران هیدرولیک H46",
      },
      {
        text: "بهران هیدرولیک H68",
        value: "بهران هیدرولیک H68",
      },
      {
        text: "بهران شهاب 30",
        value: "بهران شهاب 30",
      },
    ],
    filterMode: "tree",
    filterSearch: true,
    onFilter: (value, record) => record.name.includes(value),
    width: "30%",
  },
  {
    title: "Type",
    dataIndex: "type",
    filters: [
      {
        text: "Synthetic",
        value: "Synthetic",
      },
      {
        text: "Mineral",
        value: "Mineral",
      },
    ],
    filterMode: "tree",
    filterSearch: true,
    onFilter: (value, record) => record.type.includes(value),
    width: "30%",
  },
  {
    title: "V-Inx(c)",
    dataIndex: "viscosityindex",
    sorter: (a, b) => a.viscosityindex - b.viscosityindex,
  },
  {
    title: "V-40(c)",
    dataIndex: "viscosity40",
    sorter: (a, b) => a.viscosity40 - b.viscosity40,
  },
  {
    title: "Density",
    dataIndex: "density",
    sorter: (a, b) => a.density - b.density,
  },
  {
    title: "PourPoint",
    dataIndex: "pourpoint",
    sorter: (a, b) => a.pourpoint - b.pourpoint,
  },
  {
    title: "FlashPoint",
    dataIndex: "flashpoint",
    sorter: (a, b) => a.flashpoint - b.flashpoint,
  },
  {
    title: "Thickener",
    dataIndex: "thickener",
    filters: [
      {
        text: "Lithium Complex",
        value: "Lithium Complex",
      },
      {
        text: "Poly-Urea",
        value: "Poly-Urea",
      },
      {
        text: "PTFE",
        value: "PTFE",
      },
      {
        text: "Poly-Alkylene(PAG)",
        value: "Poly-Alkylene(PAG)",
      },
    ],
    filterMode: "tree",
    filterSearch: true,
    onFilter: (value, record) => record.thickener.includes(value),
    width: "30%",
  },
  {
    title: "Color",
    dataIndex: "color",
    filters: [
      {
        text: "Clear",
        value: "Clear",
      },
      {
        text: "Yellow",
        value: "Yellow",
      },
      {
        text: "Blue",
        value: "Blue",
      },
      {
        text: "Red",
        value: "Red",
      },
      {
        text: "Green",
        value: "Green",
      },
      {
        text: "Brown",
        value: "Brown",
      },
    ],
    filterMode: "tree",
    filterSearch: true,
    onFilter: (value, record) => record.color.includes(value),
    width: "30%",
  },
  {
    title: "NLGI",
    dataIndex: "nlgi",
    sorter: (a, b) => a.nlgi - b.nlgi,
  },
];
const data = [
  {
    key: "1",
    name: "Eni Blasia S 320",
    type: "Synthetic",
    viscosityindex: 205,
    viscosity40: 320,
    density: 1030,
    pourpoint: -33,
    flashpoint: 242,
    thickener: "Poly-Glycols",
    color: "--",
    nlgi: "",
  },
  {
    key: "25",
    name: "Eni OSO 46",
    type: "--",
    viscosityindex: 106,
    viscosity40: 46,
    density: 880,
    pourpoint: -27,
    flashpoint: 238,
    thickener: "",
    color: "Clear",
    nlgi: "",
  },
  {
    key: "2",
    name: "Shell Omala S2 G220",
    type: "--",
    viscosityindex: 100,
    viscosity40: 220,
    density: 899,
    pourpoint: -18,
    flashpoint: 240,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "3",
    name: "Enerpac",
    type: "--",
    viscosityindex: 101,
    viscosity40: "--",
    density: "--",
    pourpoint: -10,
    flashpoint: 187,
    thickener: "",
    color: "Yellow",
    nlgi: "--",
  },
  {
    key: "4",
    name: "Shell Omala S4 WE 320",
    type: "--",
    viscosityindex: 320,
    viscosity40: 321,
    density: 1069,
    pourpoint: -39,
    flashpoint: 270,
    thickener: "",
    color: "--",
    nlgi: "--",
  },
  {
    key: "5",
    name: "Mobilgear 600 XP 220",
    type: "--",
    viscosityindex: 97,
    viscosity40: 220,
    density: 0.89,
    pourpoint: -24,
    flashpoint: 240,
    thickener: "",
    color: "--",
    nlgi: "--",
  },
  {
    key: "6",
    name: "LUBCON Turmowood Oil 1",
    type: "Synthetic",
    viscosityindex: 165,
    viscosity40: 250,
    density: 0.92,
    pourpoint: -15,
    flashpoint: 260,
    thickener: "--",
    color: "Yellow - Clear",
    nlgi: "--",
  },
  {
    key: "7",
    name: "LUBCON Turmowood Oil 2",
    type: "Synthetic",
    viscosityindex: 110,
    viscosity40: 54,
    density: 0.98,
    pourpoint: -30,
    flashpoint: 270,
    thickener: "--",
    color: "Blue - Transparent",
    nlgi: "--",
  },
  {
    key: "8",
    name: "Shell Omala S2 GX 220",
    type: "--",
    viscosityindex: 100,
    viscosity40: 220,
    density: 896,
    pourpoint: -24,
    flashpoint: 260,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "9",
    name: "CLP PG 220",
    type: "Synthetic",
    viscosityindex: "--",
    viscosity40: 220,
    density: 1075,
    pourpoint: -33,
    flashpoint: 240,
    thickener: "Poly-Alkylene(PAG)",
    color: "--",
    nlgi: "--",
  },
  {
    key: "10",
    name: "Gear Oil Base 220 E1",
    type: "--",
    viscosityindex: 100,
    viscosity40: 220,
    density: 896,
    pourpoint: -24,
    flashpoint: 260,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "11",
    name: "CLP 680 Oil",
    type: "Mineral",
    viscosityindex: 94,
    viscosity40: 680,
    density: 0.909,
    pourpoint: -12,
    flashpoint: 270,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "13",
    name: "CLP PG 460",
    type: "Synthetic",
    viscosityindex: 256,
    viscosity40: 460,
    density: 1075,
    pourpoint: -41,
    flashpoint: 250,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "14",
    name: "Shell Tellus S2 M 32",
    type: "Mineral",
    viscosityindex: 99,
    viscosity40: 32,
    density: "--",
    pourpoint: -30,
    flashpoint: 218,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "15",
    name: "بهران بردبار PG 320",
    type: "Synthetic",
    viscosityindex: 220,
    viscosity40: 320,
    density: 1002,
    pourpoint: -40,
    flashpoint: 270,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "16",
    name: "بهران بردبار 220",
    type: "Synthetic",
    viscosityindex: 95,
    viscosity40: 220,
    density: 898,
    pourpoint: -15,
    flashpoint: 240,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "17",
    name: "بهران بردبار PS 220",
    type: "--",
    viscosityindex: 160,
    viscosity40: 320,
    density: 853,
    pourpoint: -30,
    flashpoint: 244,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "18",
    name: "بهران بردبار PG 220",
    type: "--",
    viscosityindex: 214,
    viscosity40: 220,
    density: 998,
    pourpoint: -40,
    flashpoint: 262,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "19",
    name: "بهران بردبار PG 460",
    type: "--",
    viscosityindex: 228,
    viscosity40: 460,
    density: 1054,
    pourpoint: -33,
    flashpoint: 276,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "20",
    name: "بهران بردبار PG 320",
    type: "--",
    viscosityindex: 220,
    viscosity40: 230,
    density: 1002,
    pourpoint: -40,
    flashpoint: 270,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "21",
    name: "بهران بردبار 680",
    type: "--",
    viscosityindex: 98,
    viscosity40: 680,
    density: 904,
    pourpoint: -9,
    flashpoint: 248,
    thickener: "Poly-Alkalin",
    color: "--",
    nlgi: "--",
  },
  {
    key: "22",
    name: "بهران هیدرولیک H46",
    type: "--",
    viscosityindex: 95,
    viscosity40: 46,
    density: 880,
    pourpoint: -27,
    flashpoint: 210,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "23",
    name: "بهران هیدرولیک H68",
    type: "--",
    viscosityindex: 95,
    viscosity40: 68,
    density: 885,
    pourpoint: -24,
    flashpoint: 220,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "24",
    name: "بهران شهاب 30",
    type: "--",
    viscosityindex: 95,
    viscosity40: 12,
    density: 890,
    pourpoint: -18,
    flashpoint: 230,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "26",
    name: "Eni Blasia 220",
    type: "--",
    viscosityindex: 95,
    viscosity40: 220,
    density: 896,
    pourpoint: -18,
    flashpoint: 232,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "27",
    name: "NILS Kes Oil Bio Top",
    type: "Synthetic",
    viscosityindex: "--",
    viscosity40: 65,
    density: 130,
    pourpoint: -33,
    flashpoint: 300,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "28",
    name: "Castrol Optigear X320",
    type: "Synthetic",
    viscosityindex: "179",
    viscosity40: 325,
    density: 852,
    pourpoint: -45,
    flashpoint: 250,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "29",
    name: "Mobilgear 630",
    type: "Synthetic",
    viscosityindex: "169",
    viscosity40: 220,
    density: 0.87,
    pourpoint: -48,
    flashpoint: 220,
    thickener: "--",
    color: "Orange",
    nlgi: "--",
  },
  {
    key: "30",
    name: "Shell Omala S4 WE 320",
    type: "Synthetic",
    viscosityindex: "230",
    viscosity40: 320,
    density: 1069,
    pourpoint: -39,
    flashpoint: 286,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "31",
    name: "Mobil SHC Gear 220",
    type: "Synthetic",
    viscosityindex: "180",
    viscosity40: 220,
    density: 0.86,
    pourpoint: -45,
    flashpoint: 233,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
  {
    key: "32",
    name: "NUTO H-46",
    type: "--",
    viscosityindex: 98,
    viscosity40: 44,
    density: 0.876,
    pourpoint: -18,
    flashpoint: 226,
    thickener: "--",
    color: "--",
    nlgi: "--",
  },
];
const onChange = (pagination, filters, sorter, extra) => {
  console.log("params", pagination, filters, sorter, extra);
};
const OilForm = () => (
  <Table
    className="oil-form"
    columns={columns}
    dataSource={data}
    onChange={onChange}
  />
);
export default OilForm;
